:zap: Devices Have Status In List Dialog

diff --git a/bin/Adb_Toolkit/scripts/apk b/bin/Adb_Toolkit/scripts/apk
--- a/bin/Adb_Toolkit/scripts/apk
+++ b/bin/Adb_Toolkit/scripts/apk
@@ -1,4 +1,4 @@
-#!/bin/bash 
+#!/bin/bash -x
 
 if  [ "$1" == "" ]; then
 zenity --error --text="Run this file from the main script" --title="Invalid run location" >/dev/null 2>&1
@@ -8,13 +8,48 @@ elif  [ "$1" == "install" ]; then
   adb start-server 2>/dev/null
   adb devices>/tmp/devices.txt
   sed -i '1d' /tmp/devices.txt
+
+  get_index(){
+        local value="$1"
+        shift
+        local arr=("$@")
+        for j in "${!arr[@]}";
+        do
+                if [[ "${arr[$j]}" == "${value}" ]]; then
+                        index="${j}"
+                        return
+                fi
+       done
+}
+  if [ "$(wc -l < /tmp/devices.txt)" != "1" ]; then
+  tr '\n' '|' < /tmp/devices.txt >/tmp/derv
+fi
+  x=()
   read -r stat < /tmp/devices.txt
   if [ "$stat" == "" ]; then
     zenity --error --text="No devices connected" --title="No device" --width=300 >/dev/null 2>&1
   else
-  dl=$(sed 's/\device//g' /tmp/devices.txt)
-  device=$(zenity --list --text="Choose a device" --column="Devices" $dl --width=300 --height=200  2>/dev/null) 
-
+    while read -r dev || [[ -n $dev ]]; do
+    IFS='|'; for i in $dev; do
+      if [ "$i" != "" ]; then
+      x+=("$(sed 's/[[:space:]].*//g' <<<$i)")
+      if [ "$(grep -o -w unauthorized <<<$i)" == "unauthorized" ]; then
+        x+=("unauthorized")
+      else
+        x+=("authorized")
+      fi
+    fi
+    done
+  done < /tmp/derv
+  #dl=$(sed 's/\device//g' /tmp/devices.txt)
+  device=$(yad --list --text="Choose a device" --column="Devices" --column="Status" ${x[@]} --print-column=1 --no-click --center --width=300 --height=200  2>/dev/null)
+  ch=$?
+  device=$(tr -d '|' <<<$device)
+  get_index "$device" "${x[@]}"
+  if [ "${x[$((index + 1))]}" == "unauthorized" ]; then
+    zenity --error --text="Selected Device Is Not Authorized \nPlease Allow USB Debugging From This PC On Your Device\n\nOperation Aborted" --title="Aborted" --width=500 >/dev/null 2>&1
+    exit 1
+  fi
 if  [ "$?" -eq 1 ]; then
 
   zenity --error --text="Operation cancelled" --title="Aborted" --width=300 >/dev/null 2>&1
