:zap::bug: Improved Device Status Options, Globbing Occurs After Putting Device Option Outside The Scope Of  Choice

diff --git a/bin/Adb_Toolkit/scripts/apk b/bin/Adb_Toolkit/scripts/apk
--- a/bin/Adb_Toolkit/scripts/apk
+++ b/bin/Adb_Toolkit/scripts/apk
@@ -30,10 +30,10 @@ elif  [ "$1" == "install" ]; then
     IFS='|'; for i in $dev; do
       if [ "$i" != "" ]; then
       x+=("$(sed 's/[[:space:]].*//g' <<<$i)")
-      if [ "$(grep -o -w unauthorized <<<$i)" == "unauthorized" ]; then
-        x+=("unauthorized")
-      else
+      if [ "$(grep -o -w device <<<$i)" == "device" ]; then
         x+=("authorized")
+      else
+        x+=("$(sed 's/.*[[:space:]]//g' <<<$i)")
       fi
       else continue
     fi
@@ -42,12 +42,7 @@ elif  [ "$1" == "install" ]; then
   #dl=$(sed 's/\device//g' /tmp/devices.txt)
   device=$(yad --list --text="Choose a device" --column="Devices" --column="Status" ${x[@]} --print-column=1 --no-click --center --width=300 --height=200  2>/dev/null)
   ch=$?
-  device=$(tr -d '|' <<<$device)
-  get_index "$device" "${x[@]}"
-  if [ "${x[$((index + 1))]}" == "unauthorized" ]; then
-    zenity --error --text="Selected Device Is Not Authorized \nPlease Allow USB Debugging From This PC On Your Device\n\nOperation Aborted" --title="Aborted" --width=500 >/dev/null 2>&1
-    exit 1
-  fi
+  
 if  [ "$?" -eq 1 ]; then
 
   zenity --error --text="Operation cancelled" --title="Aborted" --width=300 >/dev/null 2>&1
@@ -58,6 +53,12 @@ if  [ "$?" -eq 1 ]; then
       exit 1
 
       else
+        device=$(tr -d '|' <<<$device)
+  get_index "$device" "${x[@]}"
+  if [ "${x[$((index + 1))]}" != "authorized" ]; then
+    zenity --error --text="Selected Device Is Not Authorized \nPlease Allow USB Debugging From This PC On Your Device\n\nOperation Aborted" --title="Aborted" --width=500 >/dev/null 2>&1
+    exit 1
+  fi
 apk=$(zenity \
     --file-selection --file-filter="Apk | *.apk" 2>/dev/null\
  )
@@ -116,6 +117,10 @@ if  [ "$?" -eq 1 ]; then
 apk=$(adb -s $device shell pm list packages)
 
 opt=$(zenity --list --mid-search --column="Apps" ${apk} --width=600 --height=600 2>/dev/null)
+if [ "$?" != "0" ]; then
+  zenity --error --text="No Package Specified" --width=300 2>/dev/null
+  exit 1
+fi
 
 echo "$opt">/tmp/tmp.txt
 
diff --git a/bin/Adb_Toolkit/scripts/file_op b/bin/Adb_Toolkit/scripts/file_op
--- a/bin/Adb_Toolkit/scripts/file_op
+++ b/bin/Adb_Toolkit/scripts/file_op
@@ -80,10 +80,10 @@ adb start-server 2>/dev/null
     IFS='|'; for i in $dev; do
       if [ "$i" != "" ]; then
       x+=("$(sed 's/[[:space:]].*//g' <<<$i)")
-      if [ "$(grep -o -w unauthorized <<<$i)" == "unauthorized" ]; then
-        x+=("unauthorized")
-      else
+      if [ "$(grep -o -w device <<<$i)" == "device" ]; then
         x+=("authorized")
+      else
+        x+=("$(sed 's/.*[[:space:]]//g' <<<$i)")
       fi
       else continue
     fi
@@ -91,13 +91,7 @@ adb start-server 2>/dev/null
   done < /tmp/devices.txt
   #dl=$(sed 's/\device//g' /tmp/devices.txt)
   device=$(yad --list --text="Choose a device" --column="Devices" --column="Status" ${x[@]} --print-column=1 --no-click --center --width=300 --height=200  2>/dev/null)
-  ch=$?
-  device=$(tr -d '|' <<<$device)
-  get_index "$device" "${x[@]}"
-  if [ "${x[$((index + 1))]}" == "unauthorized" ]; then
-    zenity --error --text="Selected Device Is Not Authorized \nPlease Allow USB Debugging From This PC On Your Device\n\nOperation Aborted" --title="Aborted" --width=500 >/dev/null 2>&1
-    exit 1
-  fi
+  
 if  [ "$?" -eq 1 ]; then
 
   zenity --error --text="Operation cancelled" --title="Aborted" --width=300 >/dev/null 2>&1
@@ -110,7 +104,12 @@ if  [ "$?" -eq 1 ]; then
   exit 1
  
  else
-
+  device=$(tr -d '|' <<<$device)
+  get_index "$device" "${x[@]}"
+  if [ "${x[$((index + 1))]}" != "authorized" ]; then
+    zenity --error --text="Selected Device Is Not Authorized \nPlease Allow USB Debugging From This PC On Your Device\n\nOperation Aborted" --title="Aborted" --width=500 >/dev/null 2>&1
+    exit 1
+  fi
 if  [ "$1" == "" ]; then
 zenity --error --text="Run this file from the main script" --title="Invalid run location" --width=300 >/dev/null 2>&1
 
