:ambulance: Works Like Normal Now

diff --git a/bin/Adb_Toolkit/scripts/apk b/bin/Adb_Toolkit/scripts/apk
--- a/bin/Adb_Toolkit/scripts/apk
+++ b/bin/Adb_Toolkit/scripts/apk
@@ -21,21 +21,15 @@ adb start-server 2>/dev/null
   if [ "$stat" == "" ]; then
     zenity --error --text="No devices connected" --title="No device" --width=300 >/dev/null 2>&1
     exit 1
-  else
-     tr -d '\n' '|' < /tmp/devices.txt >/tmp/devices.txt
-    while read -r dev || [[ -n $dev ]]; do
-    IFS='|'; for i in $dev; do
-      if [ "$i" != "" ]; then
-      x+=("$(sed 's/[[:space:]].*//g' <<<$i)")
-      if [ "$(grep -o -w device <<<$i)" == "device" ]; then
+  else     
+    while read -r dev || [[ -n $dev ]]; do      
+      x+=("$(sed 's/[[:space:]].*//g' <<<$dev)")
+      if [ "$(grep -o -w device <<<$dev)" == "device" ]; then
         x+=("authorized")
       else
-        x+=("$(sed 's/.*[[:space:]]//g' <<<$i)")
-      fi
-      else continue
-    fi
-    done
-  done < /tmp/devices.txt
+        x+=("$(sed 's/.*[[:space:]]//g' <<<$dev)")
+      fi       
+  done < /tmp/devices.txt  
 fi
   
 if  [ "$1" == "" ]; then
@@ -97,11 +91,8 @@ apk=$(zenity \
     fi    
     elif  [ "$1" == "extract" ]; then
 
-  adb start-server 2>/dev/null
-  adb devices>/tmp/devices.txt
-  sed -i '1d' /tmp/devices.txt
-  dl=$(sed 's/\device//g' /tmp/devices.txt)
-  device=$(zenity --list --text="Choose a device" --column="Devices" $dl --width=300 --height=200 2>/dev/null)
+  device=$(yad --list --text="Choose a device" --column="Devices" --column="Status" ${x[@]} --print-column=1 --no-click --center --width=300 --height=200  2>/dev/null)
+  ch=$?
 
 if  [ "$?" -eq 1 ]; then
 
@@ -113,7 +104,12 @@ if  [ "$?" -eq 1 ]; then
       exit 1
 
       else
-
+        device=$(tr -d '|' <<<$device)
+  get_index "$device" "${x[@]}"
+  if [ "${x[$((index + 1))]}" != "authorized" ]; then
+    zenity --error --text="Selected Device Is Not Authorized \nPlease Allow USB Debugging From This PC On Your Device\n\nOperation Aborted" --title="Aborted" --width=500 >/dev/null 2>&1
+    exit 1
+  fi
       adb -s $device wait-for-device
 
 apk=$(adb -s $device shell pm list packages)
diff --git a/bin/Adb_Toolkit/scripts/font_change b/bin/Adb_Toolkit/scripts/font_change
--- a/bin/Adb_Toolkit/scripts/font_change
+++ b/bin/Adb_Toolkit/scripts/font_change
@@ -1,4 +1,4 @@
-#!/bin/bash 
+#!/bin/bash
 
 count=0
 iteration=0
@@ -17,6 +17,7 @@ fi
 
 error_handler(){
 	zenity --error --text="$reason" --title="Error" --width=200 >/dev/null 2>&1
+	exit 1
 }
 
 change_font(){
@@ -26,16 +27,15 @@ change_font(){
     adb -s $device wait-for-device
     echo "20" ; sleep 1
     echo "# Device detected" ; sleep 1
-    echo "50" ; sleep 1   
+    echo "50" ; sleep 1
     echo "# Checking for root access on device" ; sleep 1
-    echo "su" | adb shell > /tmp/is_root 2>&1
+    echo "su" | adb -s $device shell > /tmp/is_root 2>&1
     read -r root < /tmp/is_root
     if [ "$root" != "" ]; then
     	reason="Root access wasn't found \n\nPlease make sure you grant ADB root access if your device is rooted"
-    	error_handler    	
+    	error_handler
     	echo "# Aborted"
     	exit 1
-
     else
     	echo "# Root access confirmed"; sleep 1
     	echo "55" ; sleep 1
@@ -43,7 +43,7 @@ change_font(){
     	if [ "$?" != "0" ] ; then
     		reason="User aborted the operation"
     		error_handler
-    		echo "# Aborted"type
+    		echo "# Aborted"
     		exit 1
     	fi
     	echo "# Opening file browser"
@@ -58,16 +58,16 @@ change_font(){
       	if [ $font != "" ]; then
       		fontname="${font##*/}" 
       		echo "# Remounting system partition"
-      		echo "mount -o remount,rw /system" | adb -s $device shell
+      		echo "mount -o remount,rw /system" | adb -s $device shell su
       		echo "# Backing up original font file" ; sleep 5
       		echo "60" ; sleep 1
-      		echo "mv /system/fonts/$fname.ttf /system/fonts/$fname.bak" | adb -s $device shell 
+      		echo "mv /system/fonts/$fname.ttf /system/fonts/$fname.bak" | adb -s $device shell su
       		echo "# Changing device font" ; sleep 1
       		echo "70" ; sleep 5
       		adb -s $device push $font /sdcard/
       		sleep 5
-      		echo "mv /sdcard/$fontname /system/fonts/$fname.ttf" | adb -s $device shell
-      		echo "chmod 644 /system/fonts/$fname.ttf" | adb -s $device shell
+      		echo "mv /sdcard/$fontname /system/fonts/$fname.ttf" | adb -s $device shell su
+      		echo "chmod 644 /system/fonts/$fname.ttf" | adb -s $device shell su
       		echo "# Font Changed" ; sleep 2
       		if [ "$iteration" != "$count" ] ; then
       		return
@@ -124,22 +124,15 @@ elif  [ "$1" == "change_font" ]; then
   if [ "$stat" == "" ]; then
     zenity --error --text="No devices connected" --title="No device" --width=300 >/dev/null 2>&1
     exit 1
-  else
-    tr -d '\n' '|' < /tmp/devices.txt >/tmp/devices.txt
-    while read -r dev || [[ -n $dev ]]; do
-    IFS='|'; for i in $dev; do
-      if [ "$i" != "" ]; then
-      x+=("$(sed 's/[[:space:]].*//g' <<<$i)")
-      if [ "$(grep -o -w device <<<$i)" == "device" ]; then
+  else    
+    while read -r dev || [[ -n $dev ]]; do      
+      x+=("$(sed 's/[[:space:]].*//g' <<<$dev)")
+      if [ "$(grep -o -w device <<<$dev)" == "device" ]; then
         x+=("authorized")
       else
-        x+=("$(sed 's/.*[[:space:]]//g' <<<$i)")
-      fi
-      else continue
-    fi
-    done
-  done < /tmp/devices.txt
-  #dl=$(sed 's/\device//g' /tmp/devices.txt)
+        x+=("$(sed 's/.*[[:space:]]//g' <<<$dev)")
+      fi       
+  done < /tmp/devices.txt    
   device=$(yad --list --text="Choose a device" --column="Devices" --column="Status" ${x[@]} --print-column=1 --no-click --center --width=300 --height=200  2>/dev/null)
   
 if  [ "$?" -eq 1 ]; then
